<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro= "http://www.ros.org/wiki/xacro">

    <xacro:include filename="my_robotic_arm.ros2_control.xacro" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.05" radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
        </collision>    
    </link>

    <xacro:macro name="arm_link" params="prefix length radius mass">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <origin xyz="0 0 ${length/2}" rpy="0 0 0" />
                <material name="white" />
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${length-radius-0.01}" radius="${radius-0.01}"/>
                </geometry>
                <origin xyz="0 0 ${length/2+radius/2}" rpy="0 0 0" />
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                    ixx="${ (1/12.0) * mass * (3*radius*radius + length*length) }"
                    iyy="${ (1/12.0) * mass * (3*radius*radius + length*length) }"
                    izz="${ 0.5 * mass * radius*radius }"
                    ixy="0"
                    ixz="0"
                    iyz="0"/>
            </inertial>
        </link>
    </xacro:macro>

    
    <xacro:arm_link prefix="first" length="0.2" radius="0.03" mass="0.8" />
    <xacro:arm_link prefix="second" length="0.2" radius="0.03" mass="0.8" />
    <xacro:arm_link prefix="third" length="0.2" radius="0.03" mass="0.8" />

    <joint name="base_first_joint" type="revolute">
        <parent link="base_link" />
        <child link="first_link" />
        <origin xyz="0 0 0.05" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" effort="20" velocity="3.14"/>
    </joint>
    <joint name="first_second_joint" type="revolute">
        <parent link="first_link" />
        <child link="second_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="-3.14" upper="3.14" effort="20" velocity="3.14"/>
    </joint>
    <joint name="second_third_joint" type="revolute">
        <parent link="second_link" />
        <child link="third_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="-3.14" upper="3.14" effort="20" velocity="3.14"/>
    </joint>

</robot>